#!/bin/zsh -vx
#!/bin/zsh
#!/Users/moonpie/xword/debugmake Sat04Jul2020 {fcG}

clang -g -O0 -c -o xw_buildpuzz.o xw_buildpuzz.c
clang -g -O0 -c -o xw_createlinks.o xw_createlinks.c
clang -g -O0 -c -o xw_matchpuzz.o xw_matchpuzz.c
#######clang -g -O0 -c -o xw_printpuzz.o xw_printpuzz.c
clang -g -O0 -DDEBUG=1 -c -o xw_printpuzz.o xw_printpuzz.c
clang -g -O0 -c -o xw_listutil.o xw_listutil.c
clang -g -O0 -c -o xw_puzzutil.o xw_puzzutil.c
clang -g -O0 -c -o xw_tryword.o xw_tryword.c
clang -g -O0 -DDEBUG=1 -c -o xw_fillpuzz.o xw_fillpuzz.c
clang -g -O0 -c -o xw_readsort.o xw_readsort.c
clang -g -O0 -c -o xw_sizedict.o xw_sizedict.c
clang -g -O0 -c -o xword.o xword.c

####### End of /Users/moonpie/xword/debugmake #######
